 arb-dir: lib/l10n
 template-arb-file: app_es.arb
 output-dir: lib/src/core/gen/localization
 output-localization-file: app_localizations.dart
 untranslated-messages-file: lib/src/core/gen/localization/untranslated_messages.txt
 output-class: AppLocalizations

 suppress-meta-data: false
